version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /opt/docker/plex:/config
      - /media/PRN:/erotic
      - /media/PlexMedia:/movies
    restart: unless-stopped
    devices:
    - /dev/dri:/dev/dri