---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /opt/docker/radarr:/config
      - /media/PlexMedia:/movies 
      - /media/Downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped