---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /opt/docker/sonarrqbit:/config
      - /media/PlexMedia:/tv
      - /media/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped